networks:
  dentaflow_net:
    driver: bridge

volumes:
  redis_data:
  node_modules:

services:
  api:
    build: .
    container_name: dentaflow_api
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - dentaflow_net

  migrate:
    build: .
    container_name: dentaflow_migrate
    env_file: .env
    command: npm run migrate:up
    depends_on:
      api:
        condition: service_started
    networks:
      - dentaflow_net
    restart: 'no'

  redis:
    image: redis:7-alpine
    container_name: dentaflow_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - dentaflow_net

  rabbitmq:
    image: rabbitmq:4.3-alpine
    container_name: dentaflow_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - dentaflow_net
